import { existsSync, mkdirSync, unlinkSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import type { JobRecord } from './job-store.ts';
import { updateJobProgress } from './job-store.ts';
import { enqueueJob } from './job-queue.ts';
import { getMediaInfo, generateThumbnail, runFFmpeg, extractWaveformPeaks, hasAudioStream, type MediaInfo } from './ffmpeg-helpers.ts';
import { saveAssetMetadata, type Session } from './session-store.ts';
import { getFFmpegEncodeArgs } from '../hwaccel-config.js';
import { warmSession } from './proxy-cache-store.ts';

// Per-asset ingest pipeline on the `ingest` lane. One declared job graph —
// probe → conform flags → proxy → waveform peaks → thumbnail — instead of each
// step bolted where someone once needed it (Phase 5 §7.2). Steps degrade by
// asset type and are failure-isolated: a later step's failure keeps the earlier
// artifacts. Proxy (step 4) and waveform peaks (step 7) are declared here and
// filled in by their own slices; today the pipeline conforms metadata and
// (re)builds the thumbnail.
//
// `force` = the asset's bytes changed in place (dead-air): redo everything.
// Otherwise steps skip what already exists (backfill / fresh upload).

// Peaks JSON schema version — bump if the on-disk shape changes so a stale file
// can be detected/regenerated by a future reader (additive, boring format).
const PEAKS_VERSION = 1;

async function runIngest(job: JobRecord, session: Session, assetId: string, force: boolean): Promise<unknown> {
  const asset = session.assets.get(assetId);
  if (!asset) return { assetId, skipped: 'asset-gone' };

  const done: string[] = [];
  const step = (name: string) => updateJobProgress(job, { step: name, steps: done });

  // Cancel hook (F4): a delete of this asset aborts the in-flight proxy encode
  // so the ffmpeg child releases the source file. Kills only the long proxy step
  // below; probe/thumbnail are sub-second and settle on their own.
  const canceller = new AbortController();
  job.cancel = () => canceller.abort();

  const isAudio = asset.type === 'audio';
  const hasFile = !!asset.path && existsSync(asset.path);
  let mediaInfo: MediaInfo | null = null;

  // ── probe → conform flags ──
  if (!isAudio && hasFile) {
    step('probe');
    try {
      const info = await getMediaInfo(asset.path);
      mediaInfo = info;
      // Conform flags are the probe's to own — always refresh them (dead-air
      // output is CFR/SDR, so this correctly clears stale VFR/HDR after an edit).
      asset.vfr = info.vfr;
      asset.hdr = info.hdr;
      asset.rotation = info.rotation;
      // Dimensions/duration: only fill if missing — never clobber a value the
      // caller already set (dead-air owns the post-trim duration).
      if (!asset.width) asset.width = info.width;
      if (!asset.height) asset.height = info.height;
      if (!asset.duration) asset.duration = info.duration;
      saveAssetMetadata(session);
      done.push('probe');
    } catch (e) {
      console.warn(`[Ingest] probe failed for ${assetId}: ${(e as Error).message}`);
    }
  }

  // ── proxy (video) — Phase 5 step 4 (§7.1) ──
  // 960×540 (fit, aspect-preserved) H.264 with a dense 0.5s GOP (-g 15) and a
  // pinned output fps so VFR sources become CFR. Preview-only — the render path
  // always reads sources (§7.1), so the proxy fps need only match the source's
  // nominal rate for smooth scrubbing. NVENC via the system-ffmpeg HW gate when
  // available; stored on the HDD at the canonical path, warmed to the ramdisk by
  // step 5. A failed encode leaves NO artifact — the stream tier silently falls
  // back to source (§7.4), so it must never poison the earlier steps.
  if (asset.type === 'video' && hasFile) {
    const proxyPath = join(session.dir, 'proxies', `${assetId}.mp4`);
    if (force || !existsSync(proxyPath)) {
      step('proxy');
      try {
        mkdirSync(dirname(proxyPath), { recursive: true });
        const fps = asset.fps && asset.fps > 0 ? asset.fps
          : mediaInfo && mediaInfo.fps > 0 ? Math.round(mediaInfo.fps)
          : 30;
        const durationSec = asset.duration || mediaInfo?.duration || 0;
        await runFFmpeg([
          '-y',
          '-i', asset.path,
          '-vf', 'scale=960:540:force_original_aspect_ratio=decrease:force_divisible_by=2',
          ...getFFmpegEncodeArgs('proxy'),
          '-g', '15',
          '-r', String(fps),
          '-pix_fmt', 'yuv420p',
          '-c:a', 'aac', '-b:a', '128k',
          '-movflags', '+faststart',
          proxyPath,
        ], 'proxy', { timeout: Math.max(600_000, Math.round(durationSec * 3000)), signal: canceller.signal });
        asset.proxy = { status: 'ready', version: Date.now() };
        saveAssetMetadata(session);
        // No warm eviction here: onAssetMutated (the single mutation choke point)
        // already dropped the warm copy, and warmSession won't re-warm a proxy
        // until it is `ready` — so there is never a stale/partial warm copy to
        // evict at this point (§7.6 both-tier invalidation lives in onAssetMutated).
        // Warm the freshly-ready proxy into the ramdisk NOW, not just on the next
        // session-open — so a just-uploaded (or dead-air-rebuilt) asset previews at
        // RAM speed immediately. Best-effort, non-blocking; warmSession warms only
        // `ready` proxies, copies just the missing files, and the stream-guard keeps
        // it from evicting an actively-streamed session.
        warmSession(session).catch(() => {});
        done.push('proxy');
      } catch (e) {
        if (existsSync(proxyPath)) { try { unlinkSync(proxyPath); } catch { /* partial cleanup best-effort */ } }
        // Canceled (asset being deleted): abort the whole job so it settles
        // `canceled`, not `done` — leave no proxy field, don't run later steps.
        if (canceller.signal.aborted) throw e;
        asset.proxy = { status: 'failed', version: Date.now() };
        saveAssetMetadata(session);
        console.warn(`[Ingest] proxy failed for ${assetId}: ${(e as Error).message}`);
      }
    }
  }

  // ── waveform peaks (video/audio) — Phase 5 step 7 (§7.6) ──
  // ~20 peaks/sec max-amplitude envelope for the timeline waveform strip, one
  // boring JSON file per asset. Video + audio (images have no audio → skipped).
  // Streamed from ffmpeg stdout — no PCM temp file on the ramdisk. Failure-
  // isolated like the proxy step: a failed pass marks `peaks.failed` and keeps
  // every earlier artifact. A mutation (dead-air force) rebuilds it in step.
  // Silent video (screen recordings, muted exports) has no audio stream, so
  // peak extraction is a guaranteed ffmpeg failure — skip it rather than mark
  // `peaks.failed` on every ingest. Audio assets always have audio by type.
  const wantsPeaks = (asset.type === 'video' || isAudio) && hasFile
    && (isAudio || await hasAudioStream(asset.path));
  if (wantsPeaks) {
    const peaksPath = join(session.dir, 'peaks', `${assetId}.json`);
    if (force || !existsSync(peaksPath)) {
      step('peaks');
      try {
        const peaksPerSec = 20;
        const peaks = await extractWaveformPeaks(asset.path, { peaksPerSec, signal: canceller.signal });
        mkdirSync(dirname(peaksPath), { recursive: true });
        writeFileSync(peaksPath, JSON.stringify({ version: PEAKS_VERSION, peaksPerSec, peaks }));
        asset.peaks = { status: 'ready', version: Date.now() };
        saveAssetMetadata(session);
        done.push('peaks');
      } catch (e) {
        // Canceled (asset being deleted): abort the whole job so it settles
        // `canceled`, not `failed` — same contract as the proxy step.
        if (canceller.signal.aborted) throw e;
        asset.peaks = { status: 'failed', version: Date.now() };
        saveAssetMetadata(session);
        console.warn(`[Ingest] peaks failed for ${assetId}: ${(e as Error).message}`);
      }
    }
  }

  // ── thumbnail (video/image) — last step, folded out of the inline paths ──
  if (!isAudio && hasFile) {
    const thumbPath = join(session.assetsDir, `${assetId}_thumb.jpg`);
    if (force || !existsSync(thumbPath)) {
      step('thumbnail');
      try {
        await generateThumbnail(asset.path, thumbPath, asset.type === 'image');
        asset.thumbPath = thumbPath;
        saveAssetMetadata(session);
        done.push('thumbnail');
      } catch (e) {
        console.warn(`[Ingest] thumbnail failed for ${assetId}: ${(e as Error).message}`);
      }
    }
  }

  console.log(`[Ingest] ${assetId} (${asset.type}${force ? ', force' : ''}) → ${done.join(' + ') || 'nothing to do'}`);
  return { assetId, steps: done };
}

// Enqueue an ingest job for one asset. Returns the JobRecord (202 { jobId }).
export function enqueueIngest(session: Session, assetId: string, opts: { force?: boolean } = {}): JobRecord {
  return enqueueJob({
    sessionId: session.id,
    kind: 'ingest',
    lane: 'ingest',
    assetId,
    run: (job) => runIngest(job, session, assetId, opts.force === true),
  });
}
