import type { IncomingMessage, ServerResponse } from 'http';
import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { invalidateBundleCache } from '../remotion-core/render.js';
import { TEMP_DIR } from './server-config.ts';
import { parseBody, parseMultipartForm, sendJSON } from './http-helpers.ts';
import { requireSession } from './session-store.ts';
import { generateWithLLM, hasLLMProvider } from './llm-gateway.ts';
import type { SessionRoute } from './route-table.ts';

// Custom transition upload/generate/list/delete. Core stays
// transition-agnostic: no file-id special cases, no param coupling — custom
// transitions are per-user files validated and registered generically.

const CUSTOM_TRANSITIONS_DIR = join(process.cwd(), 'src', 'remotion', 'transitions', 'custom');
const TRANSITION_IMPORT_WHITELIST = ['remotion', '@remotion/shapes', 'react'];

function detectExportStyle(code: string): { style: 'default' } | { style: 'named'; name: string } | null {
  const defaultMatch = code.match(/export\s+default\s+/);
  if (defaultMatch) return { style: 'default' };
  const namedMatch = code.match(/export\s+(?:const|function)\s+(\w+)/);
  if (namedMatch) return { style: 'named', name: namedMatch[1] };
  return null;
}

function validateTransitionCode(code: string) {
  const errors: string[] = [];
  const warnings: string[] = [];
  const exportInfo = detectExportStyle(code);
  if (!exportInfo) {
    errors.push('File must contain an export (either "export default" or a named export like "export const MyTransition")');
  }
  if (!code.includes("from 'remotion'") && !code.includes('from "remotion"')) {
    errors.push('File must import from "remotion" (basic sanity check)');
  }
  const importRegex = /import\s+.*?\s+from\s+['"]([^'"]+)['"]/g;
  let match;
  while ((match = importRegex.exec(code)) !== null) {
    const pkg = match[1];
    if (pkg.startsWith('.') || pkg.startsWith('/')) continue;
    if (!TRANSITION_IMPORT_WHITELIST.includes(pkg)) {
      errors.push(`Import "${pkg}" is not allowed. Only these packages are available: ${TRANSITION_IMPORT_WHITELIST.join(', ')}`);
    }
  }
  // Check for params export (recommended)
  if (!code.match(/export\s+(?:const|let|var)\s+params\b/)) {
    warnings.push('Missing "export const params" — transition will have no configurable parameters');
  }
  // Check for meta export (recommended)
  if (!code.match(/export\s+(?:const|let|var)\s+meta\b/)) {
    warnings.push('Missing "export const meta" — transition will use filename as display name');
  }
  // Check for startFrom usage when rendering video (important for correct frame positioning)
  if ((code.includes('OffthreadVideo') || code.includes('<Video'))
    && !code.includes('startFrom') && !code.includes('fromStartFrom')) {
    warnings.push('Transition renders video but does not use fromStartFrom/toStartFrom — video clips may start from frame 0 instead of the correct position. See the transition authoring spec.');
  }
  // Spatial params must be canvas fractions, not pixels — px-scale ranges break on other orientations
  const paramsSchemaMatch = code.match(/export\s+(?:const|let|var)\s+params\s*(?::\s*\w+)?\s*=\s*(\{[\s\S]*?\});/);
  if (paramsSchemaMatch && /max\s*:\s*\d{4,}/.test(paramsSchemaMatch[1])) {
    warnings.push('A number param has a pixel-scale max (1000+) — spatial params should be canvas fractions (0-1) multiplied by useVideoConfig() width/height so the transition works on any orientation. See the transition authoring spec.');
  }
  return { valid: errors.length === 0, errors, warnings, exportInfo };
}

function regenerateBarrelFile(): void {
  if (!existsSync(CUSTOM_TRANSITIONS_DIR)) {
    mkdirSync(CUSTOM_TRANSITIONS_DIR, { recursive: true });
  }
  const files = readdirSync(CUSTOM_TRANSITIONS_DIR).filter(f => f.endsWith('.tsx') && f !== 'index.ts');
  const lines = ["// AUTO-GENERATED by upload-transition endpoint. Do not edit manually.", "import { registerTransition } from '../registry';", ""];
  files.forEach((file, i) => {
    const id = file.replace('.tsx', '');
    const code = readFileSync(join(CUSTOM_TRANSITIONS_DIR, file), 'utf-8');
    const exportInfo = detectExportStyle(code);
    const hasParams = !!code.match(/export\s+(?:const|let|var)\s+params\b/);
    const hasMeta = !!code.match(/export\s+(?:const|let|var)\s+meta\b/);
    const namedImports: string[] = [];
    if (hasParams) namedImports.push(`params as P${i}`);
    if (hasMeta) namedImports.push(`meta as M${i}`);
    const namedPart = namedImports.length > 0 ? `, { ${namedImports.join(', ')} }` : '';
    if (exportInfo?.style === 'default') {
      lines.push(`import T${i}${namedPart} from './${id}';`);
      lines.push(`registerTransition('${id}', T${i}${hasParams ? `, P${i}` : ''}${hasMeta ? `, M${i}` : ''});`);
    } else if (exportInfo?.style === 'named') {
      const allImports = [`${exportInfo.name} as T${i}`, ...namedImports];
      lines.push(`import { ${allImports.join(', ')} } from './${id}';`);
      lines.push(`registerTransition('${id}', T${i}${hasParams ? `, P${i}` : ''}${hasMeta ? `, M${i}` : ''});`);
    }
  });
  lines.push('');
  writeFileSync(join(CUSTOM_TRANSITIONS_DIR, 'index.ts'), lines.join('\n'));
}

async function handleUploadTransition(req: IncomingMessage, res: ServerResponse, sessionId: string) {
  const session = requireSession(res, sessionId);
  if (!session) return;

  try {
    let code, name;
    const contentType = req.headers['content-type'] || '';
    if (contentType.includes('multipart/form-data')) {
      // Tiny transient code file — ramdisk churn, read and unlinked immediately.
      const [fields, files] = await parseMultipartForm(req, { maxFileSize: 1 * 1024 * 1024, uploadDir: TEMP_DIR });
      const uploadedFile = files.file?.[0];
      if (!uploadedFile) {
        sendJSON(res, { error: 'Missing file' }, 400);
        return;
      }
      code = readFileSync(uploadedFile.filepath, 'utf-8');
      try { unlinkSync(uploadedFile.filepath); } catch { /* ignore cleanup errors */ }
      name = fields.name?.[0] || uploadedFile.originalFilename?.replace(/\.tsx$/, '') || 'custom-transition';
    } else {
      const body = await parseBody(req);
      code = body.code;
      name = body.name || 'custom-transition';
    }

    if (!code) {
      sendJSON(res, { error: 'No transition code provided' }, 400);
      return;
    }

    const validation = validateTransitionCode(code);
    if (!validation.valid) {
      sendJSON(res, { error: 'Validation failed', details: validation.errors }, 400);
      return;
    }

    const transitionId = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `transition-${randomUUID().slice(0, 8)}`;
    if (!existsSync(CUSTOM_TRANSITIONS_DIR)) {
      mkdirSync(CUSTOM_TRANSITIONS_DIR, { recursive: true });
    }
    writeFileSync(join(CUSTOM_TRANSITIONS_DIR, `${transitionId}.tsx`), code);
    regenerateBarrelFile();
    invalidateBundleCache();

    if (!session.customTransitions) session.customTransitions = new Map();
    session.customTransitions.set(transitionId, {
      id: transitionId,
      name,
      filename: `${transitionId}.tsx`,
      installedAt: new Date().toISOString(),
    });

    console.log(`[${sessionId}] Custom transition uploaded: ${transitionId}`);
    sendJSON(res, { success: true, transitionId, name, warnings: validation.warnings || [] });
  } catch (error: any) {
    console.error('Upload transition error:', error);
    sendJSON(res, { error: error.message }, 500);
  }
}

async function handleDeleteTransition(req: IncomingMessage, res: ServerResponse, _sessionId: string) {
  try {
    let body = '';
    for await (const chunk of req) body += chunk;
    const data = JSON.parse(body);
    const transitionId = data.transitionId;

    if (!transitionId) {
      return sendJSON(res, { error: 'Missing transitionId' }, 400);
    }

    if (transitionId.startsWith('builtin-')) {
      return sendJSON(res, { error: 'Cannot delete built-in transitions' }, 400);
    }

    const filePath = join(CUSTOM_TRANSITIONS_DIR, `${transitionId}.tsx`);
    if (!existsSync(filePath)) {
      return sendJSON(res, { error: `Transition "${transitionId}" not found` }, 404);
    }

    unlinkSync(filePath);
    regenerateBarrelFile();
    invalidateBundleCache();

    console.log(`[Transitions] Deleted custom transition: ${transitionId}`);
    sendJSON(res, { success: true, transitionId });
  } catch (error: any) {
    console.error('Delete transition error:', error);
    sendJSON(res, { error: error.message }, 500);
  }
}

async function handleListTransitions(req: IncomingMessage, res: ServerResponse, sessionId: string) {
  const session = requireSession(res, sessionId);
  if (!session) return;

  // Built-in transitions as flat list entries
  const builtInEntries = [
    { id: 'builtin-crossfade', name: 'Crossfade', description: 'Simple opacity crossfade between two clips', canvas: 'any', source: 'builtin', params: {} },
    { id: 'builtin-slide-left', name: 'Slide Left', description: 'From clip slides left, to clip slides in from right', canvas: 'any', source: 'builtin', params: {} },
    { id: 'builtin-slide-right', name: 'Slide Right', description: 'From clip slides right, to clip slides in from left', canvas: 'any', source: 'builtin', params: {} },
    { id: 'builtin-dip-to-black', name: 'Dip to Black', description: 'Dip through black between clips', canvas: 'any', source: 'builtin', params: {} },
  ];

  const customEntries: any[] = [];
  if (existsSync(CUSTOM_TRANSITIONS_DIR)) {
    const files = readdirSync(CUSTOM_TRANSITIONS_DIR).filter(f => f.endsWith('.tsx') && f !== 'index.ts');
    for (const file of files) {
      const id = file.replace('.tsx', '');
      const sessionMeta = session.customTransitions?.get(id);
      // Try to extract params and meta from source code
      const code = readFileSync(join(CUSTOM_TRANSITIONS_DIR, file), 'utf-8');
      const extractedMeta = extractTransitionMeta(code);
      const extractedParams = extractTransitionParams(code);
      customEntries.push({
        id,
        name: extractedMeta?.name || sessionMeta?.name || id,
        description: extractedMeta?.description || null,
        // Orientation compatibility declared by the transition author ('any' when unspecified)
        canvas: extractedMeta?.canvas || 'any',
        source: 'custom',
        filename: file,
        params: extractedParams || {},
        installedAt: sessionMeta?.installedAt || null,
      });
    }
  }

  // Return flat list (v2) plus legacy split for backward compat
  const transitions = [...builtInEntries, ...customEntries];
  const builtIn = ['crossfade', 'slide-left', 'slide-right', 'dip-to-black'];
  const custom = customEntries.map(e => ({ id: e.id, name: e.name, filename: e.filename, installedAt: e.installedAt }));

  sendJSON(res, { transitions, builtIn, custom });
}

// Extract meta object from transition source code (best-effort static analysis)
function extractTransitionMeta(code: string) {
  const metaMatch = code.match(/export\s+(?:const|let|var)\s+meta\s*(?::\s*\w+)?\s*=\s*(\{[\s\S]*?\});/);
  if (!metaMatch) return null;
  try {
    // Simple extraction of name and description strings
    const block = metaMatch[1];
    const nameMatch = block.match(/name\s*:\s*['"]([^'"]+)['"]/);
    const descMatch = block.match(/description\s*:\s*['"]([^'"]+)['"]/);
    const canvasMatch = block.match(/canvas\s*:\s*['"](any|landscape|portrait)['"]/);
    return { name: nameMatch?.[1] || null, description: descMatch?.[1] || null, canvas: canvasMatch?.[1] || 'any' };
  } catch { return null; }
}

// Extract params schema from transition source code (best-effort static analysis)
function extractTransitionParams(code: string) {
  const paramsMatch = code.match(/export\s+(?:const|let|var)\s+params\s*(?::\s*\w+)?\s*=\s*(\{[\s\S]*?\});/);
  if (!paramsMatch) return null;
  try {
    const block = paramsMatch[1].trim();
    if (block === '{}') return {};
    // Attempt to parse simple param definitions - returns keys with type info
    const result: Record<string, any> = {};
    const paramRegex = /(\w+)\s*:\s*\{([^}]+)\}/g;
    let m;
    while ((m = paramRegex.exec(block)) !== null) {
      const key = m[1];
      const body = m[2];
      const typeMatch = body.match(/type\s*:\s*['"](\w+)['"]/);
      const labelMatch = body.match(/label\s*:\s*['"]([^'"]+)['"]/);
      const defaultMatch = body.match(/default\s*:\s*([^,}\s]+)/);
      result[key] = {
        type: typeMatch?.[1] || 'number',
        label: labelMatch?.[1] || key,
        default: defaultMatch?.[1] ? (isNaN(Number(defaultMatch[1])) ? defaultMatch[1].replace(/['"]/g, '') : Number(defaultMatch[1])) : 0,
      };
    }
    return result;
  } catch { return null; }
}

async function handleGenerateTransition(req: IncomingMessage, res: ServerResponse, sessionId: string) {
  const session = requireSession(res, sessionId);
  if (!session) return;

  try {
    const body = await parseBody(req);
    const { description } = body;
    if (!description) {
      sendJSON(res, { error: 'description is required' }, 400);
      return;
    }

    if (!hasLLMProvider()) {
      sendJSON(res, { error: 'No LLM provider configured (set GEMINI_API_KEY or OPENAI_API_BASE_URL)' }, 400);
      return;
    }

    const systemPrompt = `You are a Remotion component author. Generate a single .tsx file that exports a React component for a video transition overlay.

RULES:
- The component renders inside a <Sequence> where frame 0 = transition start.
- Use useCurrentFrame() and useVideoConfig() from "remotion" for timing.
- Use interpolate() and Easing from "remotion" for animation curves.
- Wrap everything in an <AbsoluteFill> from "remotion".
- ONLY import from these packages: "remotion", "@remotion/shapes", "react".
- NO other imports. NO fetch/network. NO side effects. Must be deterministic.
- Export the component as either "export default" or a named export.
- The component receives optional props: { fromSrc?: string, toSrc?: string, fromAssetType?: 'video' | 'image', toAssetType?: 'video' | 'image' }
- But it can ignore all props and just use useCurrentFrame() directly.
- CANVAS INDEPENDENCE: never hardcode pixel dimensions — read width/height from useVideoConfig(). The transition must render correctly on landscape (e.g. 1920x1080) AND portrait (e.g. 1080x1920) canvases.
- If you export a "params" schema, spatial position/size params MUST be canvas fractions 0-1 (the component multiplies by useVideoConfig() width/height) — never pixel values.
- If the effect is inherently orientation-specific, declare it in the meta export: canvas: 'landscape' | 'portrait'. Otherwise omit (defaults to 'any').

Return ONLY the .tsx code, no explanation.`;

    const result = await generateWithLLM(
      `Create a transition component that does: ${description}`,
      { systemPrompt }
    );

    let code = result;
    const fenceMatch = code.match(/```(?:tsx?)?\n([\s\S]*?)\n```/);
    if (fenceMatch) code = fenceMatch[1];

    const validation = validateTransitionCode(code);
    if (!validation.valid) {
      sendJSON(res, { error: 'Generated code failed validation', details: validation.errors, code }, 400);
      return;
    }

    const name = description.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'ai-transition';
    const transitionId = `${name}-${randomUUID().slice(0, 6)}`;

    if (!existsSync(CUSTOM_TRANSITIONS_DIR)) {
      mkdirSync(CUSTOM_TRANSITIONS_DIR, { recursive: true });
    }
    writeFileSync(join(CUSTOM_TRANSITIONS_DIR, `${transitionId}.tsx`), code);
    regenerateBarrelFile();
    invalidateBundleCache();

    if (!session.customTransitions) session.customTransitions = new Map();
    session.customTransitions.set(transitionId, {
      id: transitionId,
      name: description,
      filename: `${transitionId}.tsx`,
      installedAt: new Date().toISOString(),
    });

    console.log(`[${sessionId}] Custom transition generated: ${transitionId}`);
    sendJSON(res, { success: true, transitionId, name: description, code });
  } catch (error: any) {
    console.error('Generate transition error:', error);
    sendJSON(res, { error: error.message }, 500);
  }
}

export const transitionRoutes: SessionRoute[] = [
  { method: 'POST', action: 'upload-transition', handler: handleUploadTransition },
  { method: 'GET', action: 'transitions', handler: handleListTransitions },
  { method: 'POST', action: 'generate-transition', handler: handleGenerateTransition },
  { method: 'POST', action: 'delete-transition', handler: handleDeleteTransition },
];
